export const SET_SELECTED_CURRENCY = 'SET_SELECTED_CURRENCY';
export const SET_CURRENCY_AMOUNT = 'SET_CURRENCY_AMOUNT';
export const SET_ALL_CURRENCIES_AND_AMOUNT = 'SET_ALL_CURRENCIES_AND_AMOUNT';
export const GET_CURRENCY_RATES_PROGRESS = 'GET_CURRENCY_RATES_PROGRESS';
export const GET_CURRENCY_RATES_SUCCESS = 'GET_CURRENCY_RATES_SUCCESS';
export const GET_CURRENCY_RATES_FAIL = 'GET_CURRENCY_RATES_FAIL';
